config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  resources :swimming_records, except: [:show,:edit,:update] do
    collection { post :import_times }
    collection { get :update_system }
    collection { get :results}
    collection { post :synchronise}
  end

  get 'compare_times/compare'
  get 'compare_times/search'
  get 'compare_times/show'
  get 'compare_times/show_external_times'

  resources :payments

  resources :events

  resources :parents do
    get 'cancel_parent_registration', on: :collection

  end

  resources :calendar, only: :index

  post 'parents/check_relation', as: :check

  resources :swimmer_times, except: [:show] do
    get 'search', on: :collection
    get 'best_times', on: :collection
  end

  resources :swimmers, except: :show do
    get 'swimmer_times', on: :member
    get 'medical_conditions', on: :member
    get 'payment', on: :member
    get 'cancel_swimmer_registration', on: :collection
  end

  get 'users/index'
  get 'users/profile'
  get 'users/view_dbs_status'
  get 'users/contact_users'
  post 'users/contact_users2'

  get 'home/welcome', as: :home

  get 'page/awaiting', as: :awaiting

  root 'home#welcome'

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users do
    member {get :edit_dbs_check}
    member {post :update_dbs_check}
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_filter :authenticate_user!
  # before_filter :authenticate_user!
  before_filter :set_nav_identifier

  def welcome

    @post = Post.last

  end

  private

  def set_nav_identifier

    @current_nav_identifier = :home

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/welcome.html.haml
.dashboard
  %ul.tiles
    .col1
      %li.tile.tile-big.tile-1.slideTextUp{"data-page-name" => "random-r-page", "data-page-type" => "r-page"}
        %div{style: 'margin-right:5px;'}
          -#- if @post.nil?
          %p.icon-comment Forum
          -#-else
          -#  %span{style: 'color:black;'}= @post.title
          -#  %span{style: 'float:left;padding:59px;padding-right:120px;'}= truncate(strip_tags(@post.content), length: 250)

        %div
          %p
            =link_to 'SCSC Forum', posts_path
    .col2.clearfix
      %li.tile.tile-big.tile-2.slideTextUp{"data-page-name" => "random-r-page", "data-page-type" => "r-page"}
        %div
          %p.icon-time Times
        %div
          %p
            =link_to 'Search Times', swimmer_times_path
    - if (current_user.role? 'Administrator')
      .col3.clearfix
        %li.tile.tile-big.tile-1.slideTextUp{'data-page-name' => 'random-r-page', 'data-page-type' => 'r-page'}
          %div
            %p.icon-user Users
          %div
            %p
              =link_to 'Manage Users', users_path
    -else
      .col3.clearfix
        %li.tile.tile-big.tile-1.slideTextUp{'data-page-name' => 'random-r-page', 'data-page-type' => 'r-page'}
          %div
            %p.icon-user Profile
          %div
            %p
              =link_to 'View Your Profile', users_profile_path
    -#- if current_user.check_roles %w(Swimmer Parent Welfare\ Officer)
    .col1.clearfix
      %li.tile.tile-small.tile-6.slideTextRight{"data-page-name" => "random-restored-page", "data-page-type" => "s-page"}
        %div
          %p
            =link_to 'Medical', swimmers_path
        %div
          %p.icon-ambulance= link_to '', swimmers_path
        -#- if current_user.role? 'Welfare Officer'
      %li.tile.tile-small.last.tile-2.slideTextLeft{"data-page-name" => "random-restored-page", "data-page-type" => "s-page"}
        %div
          %span.icon-eye-open
        %div
          %p
            =link_to 'DBS', users_view_dbs_status_path
      -#- if current_user.check_roles %w(Administrator Committee Swimmer Parent)
    .col2.clearfix
      %li.tile.tile-small.tile-1.slideTextRight{"data-page-name" => "random-restored-page", "data-page-type" => "s-page"}
        %div
          %p
            - if current_user.role? 'Swimmer'
              = link_to 'Payment', payment_swimmer_path(current_user.swimmer)
            - else
              = link_to 'Payment', payments_path
        %div
          %p.icon-mondy Payments
      -#- if current_user.role? 'Welfare Officer'
      %li.tile.tile-small.last.tile-4.slideTextLeft{"data-page-name" => "random-restored-page", "data-page-type" => "s-page"}
        %div
          %p.icon-calendar-empty Events
        %div
          %p
            =link_to 'Events', events_path

    .col3.clearfix
      %li.tile.tile-small.tile-5.slideTextRight{"data-page-name" => "random-restored-page", "data-page-type" => "s-page"}
        %div
          %p
            =link_to 'Best Times', best_times_swimmer_times_path
        %div
          %p Best Times
      %li.tile.tile-small.last.tile-2.slideTextRight{"data-page-name" => "random-restored-page", "data-page-type" => "s-page"}
        %div
          %p
            = link_to 'Calendar', calendar_index_path
        %div
          %p.icon-calendar Calendar