config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  resources :swimming_records, except: [:show,:edit,:update] do
    collection { post :import_times }
    collection { get :update_system }
    collection { get :results}
    collection { post :synchronise}
  end

  get 'compare_times/compare'
  get 'compare_times/search'
  get 'compare_times/show'
  get 'compare_times/show_external_times'

  resources :payments

  resources :events

  resources :parents do
    get 'cancel_parent_registration', on: :collection

  end

  resources :calendar, only: :index

  post 'parents/check_relation', as: :check

  resources :swimmer_times, except: [:show] do
    get 'search', on: :collection
    get 'best_times', on: :collection
  end

  resources :swimmers, except: :show do
    get 'swimmer_times', on: :member
    get 'medical_conditions', on: :member
    get 'payment', on: :member
    get 'cancel_swimmer_registration', on: :collection
  end

  get 'users/index'
  get 'users/profile'
  get 'users/view_dbs_status'
  get 'users/contact_users'
  post 'users/contact_users2'

  get 'home/welcome', as: :home

  get 'page/awaiting', as: :awaiting

  root 'home#welcome'

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users do
    member {get :edit_dbs_check}
    member {post :update_dbs_check}
  end

end

app/models/swimmer.rb
class Swimmer < ActiveRecord::Base
  belongs_to :user
  has_many :payments, dependent: :destroy
  has_one :medical_condition, dependent: :destroy
  accepts_nested_attributes_for :medical_condition, allow_destroy: true
  has_many :swimmer_times, dependent: :destroy
  has_and_belongs_to_many :parents
  has_one :address, as: :addressable, dependent: :destroy
  accepts_nested_attributes_for :address, allow_destroy: true
  validates :asa_category,:asa_number,:ethnic,:date_of_birth,:sex,:photo_consent,:current_squad, presence: true
  validate :date_cannot_be_in_the_future
  validates :asa_number, numericality: true
  before_destroy :check_parents




  ETHNICITY = %w(White White-British White-Irish Asian-Indian Asian-Pakistan Asian-Other Asian-Bangladeshi Chinese Mixed-White\ And\ Asian Mixed-White\ And\ Black\ Caribbean Black-Caribbean Black-African Black-Other Other\ Ethnic\ Group)
  ASA_CATEGORY = %w(Paid\ Cat3 Club\ Paid\ Cat3)
  CURRENT_SQUAD = %w(A-Squad B-Squad C-Squad Youth Masters)

  # before_destroy { |swimmer| Parent.destroy_all "swimmer_id = #{swimmer.id}" }


  scope :sex, lambda {|sex| where(sex: sex)}
  scope :user, lambda {|user| where(user: user)}


  def date_cannot_be_in_the_future
    errors.add(:date_of_birth, "can't be in the future") if
        !date_of_birth.blank? and date_of_birth > Date.today
  end

  def swimmer_name
    u = User.find(user_id)
    u.combined_name
  end


  def details_of_times

    self.swimmer_times.order(:date,:times).group_by {|e| [e.stroke,e.distance,e.course]}
  end

  def check_parents

    self.parents.each do |parent|
      User.destroy(parent.user_id) if parent.swimmers.size <= 1
    end

  end


end

app/controllers/swimmers_controller.rb
class SwimmersController < ApplicationController
  before_action :set_swimmer, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  before_filter :stop_administrator, only: [:index,:medical_conditions]
  skip_before_filter :authenticate_user!, only: [:new,:cancel_swimmer_registration,:create]
  skip_authorize_resource only: [:new,:cancel_swimmer_registration,:create]
  before_filter :set_nav_identifier


  def swimmer_times

    @swimmer = Swimmer.find(params[:id])
    @swimmer_times = @swimmer.details_of_times

    time = SwimmerTime.where(swimmer_id:params[:id]).sort_by {|date| date.date}
     @years_ago = Time.now.year - time.first.date.year unless time.empty?

  end

  # GET /swimmers
  # GET /swimmers.json
  def index
    if current_user.role? 'Welfare Officer'
      @swimmers = Swimmer.all
    elsif current_user.role? 'Swimmer'
      redirect_to medical_conditions_swimmer_path(current_user.swimmer.id)
    else
      @swimmers = Parent.find(current_user.parent.id).swimmers
    end

  end

  # GET /swimmers/1
  # GET /swimmers/1.json
  # def show
  # end

  # GET /swimmers/new
  def new
    user = User.where(id: session[:temp_swimmer_user_id])
    if user.empty?
      session[:temp_swimmer_user_id] = nil
      redirect_to new_user_registration_path, notice: 'Sign Up'

    elsif session[:temp_swimmer_user_id]
    @swimmer = Swimmer.new
    @swimmer.build_address
    @swimmer.build_medical_condition
    @swimmer.medical_condition.build_address
    else
      redirect_to new_user_registration_path, notice: 'Sing Up'
    end
  end

  # GET /swimmers/1/edit
  def edit
  end

  def medical_conditions

    if current_user.role? 'Welfare Officer'
      @swimmer = Swimmer.find(params[:id])
    elsif current_user.role? 'Swimmer'
       @swimmer = Swimmer.find(current_user.swimmer.id)
    else
      swimmers = Parent.find(current_user.parent.id).swimmers
      if swimmers.ids.include? params[:id].to_i
        @swimmer = Swimmer.find(params[:id])
      end
    end
  end

  def payment
    @swimmer = Swimmer.find(params[:id])
  end


  # POST /swimmers
  # POST /swimmers.json
  def create
    @swimmer = Swimmer.new(swimmer_params)

    respond_to do |format|
      if @swimmer.save
        #format.html { redirect_to @swimmer, notice: 'Swimmer was successfully created.' }
        format.html { redirect_to :awaiting, notice: 'Sign up successful' }
        session[:temp_swimmer_user_id] = nil


        format.json { render :show, status: :created, location: @swimmer }
      else
        format.html { render :new }
        format.json { render json: @swimmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swimmers/1
  # PATCH/PUT /swimmers/1.json
  def update
    respond_to do |format|
      if @swimmer.update(swimmer_params)
        format.html { redirect_to users_profile_url, notice: 'Your details was successfully updated.' }
        format.json { render :show, status: :ok, location: @swimmer }
      else
        format.html { render :edit }
        format.json { render json: @swimmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swimmers/1
  # DELETE /swimmers/1.json
  def destroy
    @swimmer.destroy
    respond_to do |format|
      format.html { redirect_to swimmers_url, notice: 'Swimmer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def cancel_swimmer_registration
    user = User.find(session[:temp_swimmer_user_id])
    user.destroy
    session[:temp_swimmer_user_id] = nil
    redirect_to new_user_registration_url, notice: "Registration canceled!\n Please try again"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swimmer
      @swimmer = Swimmer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swimmer_params
      params.require(:swimmer).permit(:asa_number,:email_parent, :asa_category, :date_of_birth, :sex, :photo_consent, :current_squad, :user_id,:ethnic, address_attributes: [:line1, :line2, :city, :postcode, :telephone, :emergency_contact, :addressable_id, :addressable_type],medical_condition_attributes: [:medical_history,:medication,:allergies,:doctor,:disability,address_attributes: [:line1, :line2, :city, :postcode, :telephone, :emergency_contact, :addressable_id, :addressable_type]])
    end
    def stop_administrator


      unless ((current_user.role? 'Welfare Officer')||( current_user.role? 'Parent') ||(current_user.role? 'Swimmer' ))
        redirect_to :home, alert: 'You are not authorized to access this page!'
      end

    end
    def set_nav_identifier
  
      @current_nav_identifier = :medical
  
    end

end

app/helpers/swimmers_helper.rb
module SwimmersHelper





end

app/views/swimmers/_form.html.haml
.row

  .sign-up.col-md-8.col-md-offset-2
    %br

    = bootstrap_form_for(@swimmer,html: {onsubmit:'return go()' } )do |f|
      -#- if @swimmer.errors.any?
      -#  #error_explanation
      -#    %h2= "#{pluralize(@swimmer.errors.count, "error")} prohibited this swimmer from being saved:"
      -#    %ul
      -#      - @swimmer.errors.full_messages.each do |msg|
      -#        %li= msg

      .col-md-4
        =f.text_field :asa_number, label: 'ASA Number:', required: true
        =f.text_field :asa_category,label: 'ASA Category:', required: true
        -#=f.select :asa_category,Swimmer::ASA_CATEGORY,label: 'ASA Category:'
        =f.select :current_squad,Swimmer::CURRENT_SQUAD, label: 'Current Squad:'
        =f.select :ethnic, Swimmer::ETHNICITY, label:'Ethnicity:'
        =f.text_field :date_of_birth,required: true

        =f.form_group :email_parent do
          =f.check_box :email_parent


        = f.form_group :sex, label: { text: 'Gender:' } do
          = f.radio_button :sex, 'Male', label: 'Male', inline: true
          = f.radio_button :sex,'Female', label: 'Female', inline: true

        = f.form_group :photo_consent, label: { text: 'Photo Consent:' } do
          = f.radio_button :photo_consent, 'Yes', label: 'Yes', inline: true
          = f.radio_button :photo_consent, 'No', label: 'No', inline: true

        = f.hidden_field :user_id, value: session[:temp_swimmer_user_id] unless current_user
        = f.hidden_field :user_id, value: current_user.id if current_user
        %hr
        = f.fields_for :address do |address|
          .alert.alert-warning
            %h4 Your Address
          = render partial: 'shared/address_form', locals: {f: address}
        %br
        .alert.alert-warning
          %h4 Medical Conditions

        = f.fields_for :medical_condition do |condition|
          = condition.text_area :medical_history
          = condition.text_area :medication
          = condition.text_field :allergies
          = condition.select :disability, MedicalCondition::DISABILITY
          = condition.text_field :doctor
          = condition.fields_for :address do |address|
            .alert.alert-warning
              %h4 Your Doctor's Address
            = render partial: 'shared/address_form', locals: {f: address}



        .actions
          %br
          = f.submit 'Submit', :class=>'btn btn-primary btn-lg active'
          %br
          %br
          =link_to 'Cancel Registration', cancel_swimmer_registration_swimmers_path(:temp_swimmer_user_id),data: {confirm: 'Are you sure?'}, class: 'col-md-10 btn  btn-danger' unless current_user
          %br
          %br
            -#=button_tag   'Cancel', user_path(:temp_swimmer_user_id), method: :delete, data: {confirm: 'Are you sure'}, class: 'btn btn-lg btn-danger'
        -#= button_to  'Cancel', { action: 'destroy', id: :temp_swimmer_user_id }, method: :delete, data: {confirm: 'Are you sure?'}

app/views/swimmers/edit.html.haml
.container
  .page-header{style: 'text-align:center'}
    %h2 Edit Your Profile
  = render 'form'
\|
-#= link_to 'Back', swimmers_path

app/views/swimmers/index.html.haml
-#%h1 Listing swimmers
-#
-#%table.table.table-striped.table-responsive.table-nonfluid.table-customstyle.table-hover
-#  %tr
-#    %th Asa number
-#    %th Asa category
-#    %th Date of birth
-#    %th Sex
-#    %th Photo consent
-#    %th Current squad
-#    %th User
-#    %th
-#    %th
-#    %th
-#
-#  - @swimmers.each do |swimmer|
-#    %tr
-#      %td= swimmer.asa_number
-#      %td= swimmer.asa_category
-#      %td= swimmer.date_of_birth
-#      %td= swimmer.sex
-#      %td= swimmer.photo_consent
-#      %td= swimmer.current_squad
-#      %td= swimmer.user
-#      %td= link_to 'Show', swimmer
-#      %td= link_to 'Edit', edit_swimmer_path(swimmer)
-#      %td= link_to 'Destroy', swimmer, :method => :delete, :data => { :confirm => 'Are you sure?' }
-#
-#%br

.container
  .row
    .col-md-8.col-md-offset-2
      %h3 Swimmers
      %table.table.table-striped.table-responsive.table-customstyle
        %thead

          %tr
            %th First Name
            %th Last Name
            %th Email
            %th Action

        - @swimmers.each do |swimmer|
          %tbody
            %tr
              %td= swimmer.user.first_name
              %td= swimmer.user.last_name
              %td= swimmer.user.email
              %td
                %a.btn.btn-success{href: medical_conditions_swimmer_path(swimmer.id)} view

app/views/swimmers/medical_conditions.html.haml
.container
  .row
    %br
    .col-md-5.col-md-offset-3
      .alert.alert-info.text-center
        %h4= "#{@swimmer.user.first_name} #{@swimmer.user.last_name}"

      %table.table
        %tr
          %th First Name
          %td= @swimmer.user.first_name
        %tr
          %th Last Name
          %td= @swimmer.user.last_name
        %tr
          %th Email
          %td= @swimmer.user.email
        %tr
          %th Date of birth
          %td= @swimmer.date_of_birth

  .row
    .col-md-5.col-md-offset-3
      .alert.alert-info.text-center
        %h4 Medical Conditions
      %table.table
        %tr
          %th Medical history
          %td= @swimmer.medical_condition.medical_history
        %tr
          %th Medication
          %td= @swimmer.medical_condition.medication
        %tr
          %th Allergies
          %td= @swimmer.medical_condition.allergies
        %tr
          %th Disability
          %td= @swimmer.medical_condition.disability
        %tr
          %th Doctor
          %td= @swimmer.medical_condition.doctor

  .row
    .col-md-5.col-md-offset-3
      .alert.alert-info.text-center
        %h4 Doctor's Address
      %table.table
        %tr
          %th Line1
          %td= @swimmer.medical_condition.address.line1
        %tr
          %th Line2
          %td= @swimmer.medical_condition.address.line2
        %tr
          %th City
          %td= @swimmer.medical_condition.address.city
        %tr
          %th Postcode
          %td= @swimmer.medical_condition.address.postcode
        %tr
          %th Telephone
          %td= @swimmer.medical_condition.address.telephone
        %tr
          %th Emergency Contact
          %td= @swimmer.medical_condition.address.emergency_contact
        %tr

  .row
    .col-md-2.col-md-offset-3
      =link_to('<i class="icon-circle-arrow-left"></i> Back'.html_safe,swimmers_path)

      %br

        -#=button_to  'Delete', user_path(@user), method: :delete, data: {confirm: 'Are you sure'},id:'approve-btn', class: 'col-md-2-col-md-offset-3 btn btn-lg btn-danger'
        -#%a.btn.btn-success.btn-lg{href:edit_user_path(@user) , role: "button"} Generate User Report

    %br

app/views/swimmers/new.html.haml
.container
  -#.page-header{style: 'text-align:center'}
  -#  %h2 Register
  = render 'form'

app/views/swimmers/payment.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      %h3 Payment History
      %table.table.table-striped.table-responsive.table-customstyle
        %thead
          %tr
            %th Swimmer
            %th Details
            %th Amount
            %th Due date
            %th Paid date
            %th


        - @swimmer.payments.each do |payment|
          %tr
            %td= payment.swimmer.swimmer_name
            %td= truncate(strip_tags(payment.details), length: 10)
            %td= payment.amount
            %td= payment.due_date
            - if payment.paid
              %td= payment.paid_date
            -else
              %td= 'N/A' unless payment.paid
            %td
              %a.btn.btn-success{href: payment_path(payment), role: 'button'} View
            -#%td= link_to 'Show', payment
            -#%td= link_to 'Edit', e
            -#%td= link_to 'Destroy', payment, :method => :delete, :data => { :confirm => 'Are you sure?' }

  .row
    .col-md-5.col-md-offset-2
      %br
      %br

%br
%br

app/views/swimmers/swimmer_times.html.erb
<script src="http://code.highcharts.com/modules/exporting.js"></script>
<div class="container">
  <!--<div class="alert alert-success">-->
  <!--<h2>-->
  <!--<%= "#{@swimmer.swimmer_name}'s Times" %>-->
  <!--</div>-->

  <script>

      $(function(){



          new Highcharts.Chart({

              chart: {
                  renderTo: 'times_charts'
              },
              title: {

                  text: '<%= "#{@swimmer.swimmer_name} times" %>'

              },
              xAxis: {
                  type: "datetime",
                  dateTimeLabelFormats:{
                      month: '%Y'
                  }
//                  formatter: function() {
//                      return Highcharts.dateFormat('%Y %a %b', this.value);
//                  }
              },
              yAxis: {
                  title: {
                      text: 'Times(seconds)'
                  }
              },
              tooltip: {
                  headerFormat: '<b>{series.name}</b><br>',
                  pointFormat: '{point.x:%Y %b %e}:   {point.y} Sec'
              },
              series: [

                  <% @swimmer_times.keys.each_with_index do |key,index| %>
                  {
                      name: '<%= "#{key.first} #{key.second}m #{key.third}" %>',
                      pointInterval: <%= 1.year * 1000 %>,
                      pointStart: <%= @years_ago.years.ago.to_i * 1000  %>,
                      data: [
                          <%  @swimmer_times[key].map do |item| %>

                          [Date.UTC(<%= item.date.year %>,<%= item.date.month - 1 %>,<%= item.date.day %>),<%= item.times_in_seconds %>],

                          <% end %>

                      ],
                      <% if index > 5 %>
                      visible: false
                      <% end %>
                  },
                  <% end %>

              ]

          });

      });



  </script>

  <div class="row" style="margin-top: 25px">
    <div class="col-md-10 col-md-offset-1" id="times_charts" style="margin-bottom:30px"></div>
  </div>

  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <% @swimmer_times.keys.each do |item| %>
          <div class="alert alert-info">
            <caption>
              <%= "Times for #{item.first} Stroke #{item.second} meter" %>
            </caption>
          </div>
          <table class="table-bordered table-condensed table table-striped table-responsive table-customstyle">
            <thead>
            <th>Age</th>
            <th>Times</th>
            <th>Course</th>
            <th>Meet</th>
            <th>Venue</th>
            <th>Date</th>
            </thead>
            <% values = Hash.new %>
            <tbody>
            <% @swimmer_times[item].each do |item| %>
                <tr>
                <td>
                  <%= item.age %>
                </td>
                <td>
                  <%= item.convert_times %>
                </td>
                <td>
                  <%= item.course %>
                </td>
                <td>
                  <%= item.meet %>
                </td>
                <td>
                  <%= item.venue %>
                </td>
                <td>
                  <%= item.date %>
                </td>
                <% #- values[item.date.year] = (item.times/10) %>
                </tr>
            <% end %>
            </tbody>
          </table>

      <% end %>
    </div>
  </div>
</div>

app/views/swimmers/swimmer_times.html.haml
-#.container
-#
-#  .alert.alert-success
-#    %h2= "#{@swimmer.swimmer_name}'s Times"
-#  %br
-#  :javascript
-#    $(function(){
-#
-#        new Highcharts.Chart({
-#
-#            chart: {
-#                renderTo: 'times_charts'
-#            },
-#            title: {
-#
-#                text: 'Swimmer Times'
-#
-#            },
-#            xAxis: {
-#               type: "date"
-#            },
-#            yAxis: {
-#                title: {
-#                  text: 'Times(seconds)'
-#                }
-#            },
-#            series: [{
-#
-#                pointInterval:  "#{1.day.ago.year}",
-#
-#                data: [1, 2, 5, 7, 3]
-#
-#            }]
-#
-#
-#
-#
-#        });
-#
-#
-#    });
-#
-#  .row
-#    #times_charts.col-md-10.col-md-offset-1
-#
-#  .row
-#    .col-md-10.col-md-offset-1
-#      -@swimmer_times.keys.each do |item|
-#        .alert.alert-info
-#          %caption= "Times for #{item.first} Stroke #{item.second} meter"
-#        %table.table-bordered.table-condensed.table.table-striped.table-responsive.table-customstyle
-#          %thead
-#            %th Age
-#            %th Times
-#            %th Course
-#            %th Venue
-#            %th Date
-#          - values = Hash.new
-#          - @swimmer_times[item].each do |item|
-#            %tbody
-#              %td= item.age
-#              %td= item.convert_times
-#              %td= item.course
-#              %td= item.venue
-#              %td= item.date
-#              -#- values[item.date.year] = (item.times/10)
-#
-#        -#= line_chart({20.day.ago => 5, 1368174456 => 10, "2013-05-07 00:00:00 UTC" => 7}, id:'Iman')
-#        -#= values
-#        -#= @swimmer_times
-#        -#= line_chart(Swimmer.first.swimmer_times.order(:date,:times).group_by {|e| [e.stroke,e.distance]})
-#        = line_chart [{2012 => 10},{2014 => 20}], id:'Iman'
-#
-#        -#= line_chart({2012 => 10, 2010 => 20}, id:'Iman')
-#
-#