config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  resources :swimming_records, except: [:show,:edit,:update] do
    collection { post :import_times }
    collection { get :update_system }
    collection { get :results}
    collection { post :synchronise}
  end

  get 'compare_times/compare'
  get 'compare_times/search'
  get 'compare_times/show'
  get 'compare_times/show_external_times'

  resources :payments

  resources :events

  resources :parents do
    get 'cancel_parent_registration', on: :collection

  end

  resources :calendar, only: :index

  post 'parents/check_relation', as: :check

  resources :swimmer_times, except: [:show] do
    get 'search', on: :collection
    get 'best_times', on: :collection
  end

  resources :swimmers, except: :show do
    get 'swimmer_times', on: :member
    get 'medical_conditions', on: :member
    get 'payment', on: :member
    get 'cancel_swimmer_registration', on: :collection
  end

  get 'users/index'
  get 'users/profile'
  get 'users/view_dbs_status'
  get 'users/contact_users'
  post 'users/contact_users2'

  get 'home/welcome', as: :home

  get 'page/awaiting', as: :awaiting

  root 'home#welcome'

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users do
    member {get :edit_dbs_check}
    member {post :update_dbs_check}
  end

end

app/models/swimmer_time.rb
class SwimmerTime < ActiveRecord::Base
  STROKE_TYPES = %w(Backstroke Breaststroke Butterfly Individual\ Medley Medley Freestyle)
  AGE = *7..30
  DISTANCE = [25,50,100,200,400,800,1500]
  YEAR = (30.years.ago.year..Time.new.year).to_a

  M = %w(00 01 02 03 04 05 06 07 08 09)
  MINUTES = M + (10...60).to_a
  SECONDS =  M + (10...60).to_a
  MILLI_SECONDS =  M + (10...100).to_a
  belongs_to :swimmer
  validates :venue,:date, presence: true
  validate :date_cannot_be_in_the_future
  validate :times_can_not_be_zero

  attr_accessor :minutes, :seconds, :milli_seconds, :temp_swimmer
  before_save :insert_into_times
  # before_create :insert_into_times
  before_save :calculate_age

  scope :stroke, lambda {|stroke| where(stroke: stroke)}
  scope :distance, lambda {|distance| where(distance: "#{distance}")}
  scope :date, lambda {|year| where('extract(year from date) = ?',"#{year}")}
  scope :swimmer, lambda {|swimmer| where(swimmer: swimmer)}
  scope :age, lambda {|age| where(age: age)}



  def age_group
    #self.date.year - self.swimmer.date_of_birth.year
    date.year.to_i - swimmer.date_of_birth.year.to_i
  end

  def convert_times
    min = self.times/6000
    sec = (self.times % 6000 )/ 100
    milli_sec = ((self.times % 6000) % 100)
    "#{min}:#{sec}:#{milli_sec}"
  end

  def times_in_seconds
    # min = self.times / 600
    # sec = (self.times % 600) / 60
    # min * 60 + sec
    times / 100
  end




  def insert_into_times
    times = self.minutes.to_i*6000 + self.seconds.to_i*100 + milli_seconds.to_i
    self.times = times

  end

  def calculate_age
    self.age = date.year - swimmer.date_of_birth.year

  end

  def self.go

    SwimmerTime.all.group(:stroke).first

  end

  def self.best_times gender

    swimmer_time = SwimmerTime.swimmer(Swimmer.where(sex: gender)).order(:times).group_by{|e|[e.stroke,e.distance,e.age]}

  end

  def date_cannot_be_in_the_future
    errors.add(:date, "date can't be in the future") if
        !date.blank? and date > Date.today
  end

  def times_can_not_be_zero
    times = self.minutes.to_i*6000 + self.seconds.to_i*100 + milli_seconds.to_i

    puts times

    errors.add(:times, 'Time can not be zero') if (times == 0)
  end


end

app/controllers/swimmer_times_controller.rb
class SwimmerTimesController < ApplicationController
  before_action :set_swimmer_time, only: [:show, :edit, :update, :destroy]
  before_filter :set_nav_identifier
  # load_and_authorize_resource


  # GET /swimmer_times
  # GET /swimmer_times.json
  def index
    # @swimmer_times = SwimmerTime.all
    @swimmer_time = SwimmerTime.new
    @swimmers = Swimmer.all
    @females = SwimmerTime.best_times 'Female'
    @males = SwimmerTime.best_times 'Male'

  end

  def best_times
    @females = SwimmerTime.best_times 'Female'
    @males = SwimmerTime.best_times 'Male'
  end


  # GET /swimmer_times/1
  # GET /swimmer_times/1.json
  def show

  end

  #Get
  def search


     @swimmers = Swimmer.sex(params[:gender]) unless params[:gender] == 'All'
     @swimmers = Swimmer.all if params[:gender] == 'All'
     @swimmer_times = SwimmerTime.swimmer @swimmers


    filtering_params(params).each do |key, value|
      @swimmer_times = @swimmer_times.public_send(key, value) if value.present? && value != 'All'
    end


     respond_to do |format|

         format.js

     end

  end

  # GET /swimmer_times/new
  def new
    @swimmer_time = SwimmerTime.new
    # @swimmers = User.swimmers
    @swimmers = Swimmer.all

  end

  # GET /swimmer_times/1/edit
  def edit
    #@swimmer_time = SwimmerTime.new(swimmer_time_params)
    @swimmers = Swimmer.all
    swimmer_time = SwimmerTime.find(params[:id])
    @swimmer = swimmer_time.swimmer

  end

  # POST /swimmer_times
  # POST /swimmer_times.json
  def create
    @swimmer_time = SwimmerTime.new(swimmer_time_params)

    respond_to do |format|
      if @swimmer_time.save
        # format.html { redirect_to @swimmer_time, notice: 'Swimmer time was successfully created.' }
        format.js

        # format.json { render :show, status: :created, location: @swimmer_time }
      else
        # format.html { render :new }

        format.js { render 'create_failure' }
        # format.json { render json: @swimmer_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swimmer_times/1
  # PATCH/PUT /swimmer_times/1.json
  def update
    respond_to do |format|
      if @swimmer_time.update(swimmer_time_params)
        format.html { redirect_to swimmer_times_path, notice: 'Swimmer time was successfully updated.' }
        format.js
        format.json { render :show, status: :ok, location: @swimmer_time }
      else
        swimmer_time = SwimmerTime.find(params[:id])
        @swimmer = swimmer_time.swimmer
        format.html { render :edit }
        format.json { render json: @swimmer_time.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swimmer_times/1
  # DELETE /swimmer_times/1.json
  def destroy
    @id = @swimmer_time.id
    @swimmer_time.destroy
    respond_to do |format|
      format.html { redirect_to swimmer_times_url, notice: 'Swimmer time was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swimmer_time
      @swimmer_time = SwimmerTime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swimmer_time_params
      params.require(:swimmer_time).permit(:swimmer_id, :stroke, :distance, :times,:course, :club,:meet, :venue,:age, :date, :minutes,:seconds,:milli_seconds,:asa_top_ten,:bml,:asa_meet)
    end
    def filtering_params(params)
       params.slice(:stroke,:date,:distance,:age)
      # params.slice(:length)
    end

  def set_nav_identifier
    @current_nav_identifier = :times
  end
end

app/helpers/swimmer_times_helper.rb
module SwimmerTimesHelper
end

app/views/swimmer_times/_best_times.html.haml
#best_timess
  -#
  -#.alert.alert-success
  -#  %h2 Best Club Times
  %br

  .row
    .col-md-10.col-md-offset-1
      .alert.alert-warning.text-center
        %h3 Girls
      -@females.keys.each do |item|
        .alert.alert-info.text-center
          %caption= " #{item.first} STROKE\t #{item.second} Meters\t"
        %table.table-bordered.table-condensed.table.table-striped.table-responsive.table-customstyle
          %thead
            %th Name
            %th Time
            %th Meet
            %th Venue
            -#%th Age
            %th Date
          %tbody
            %td= link_to @females[item].first.swimmer.swimmer_name, swimmer_times_swimmer_path(@females[item].first.swimmer_id)
            %td= @females[item].first.convert_times
            %td= @females[item].first.meet
            %td= @females[item].first.venue
            -#%td= @females[item].first.age
            %td= @females[item].first.date

    .col-md-10.col-md-offset-1
      .alert.alert-warning.text-center
        %h3 Boys
      - @males.keys.each do |item|
        .alert.alert-info.text-center
          %caption= " #{item.first} STROKE\t #{item.second} Meters\t"
        %table.table-bordered.table-condensed.table.table-striped.table-responsive.table-customstyle
          %thead
            %th Name
            %th Time
            %th Meet
            %th Venue
            -#%th Age
            %th Date
          %tbody
            %td= link_to @males[item].first.swimmer.swimmer_name, swimmer_times_swimmer_path(@males[item].first.swimmer_id)
            %td= @males[item].first.convert_times
            %td= @males[item].first.meet
            %td= @males[item].first.venue
            -#%td= @males[item].first.ag
            %td= @males[item].first.date

app/views/swimmer_times/_form.html.haml
.times

  = bootstrap_form_for @swimmer_time, remote: true do |f|
    - if @swimmer_time.errors.any?
      #error_explanation
        %h2= "#{pluralize(@swimmer_time.errors.count, "error")} prohibited this swimmer_time from being saved:"
        %ul
          - @swimmer_time.errors.full_messages.each do |msg|
            %li= msg
    .row
      .input.col-md-2
        = f.collection_select(:swimmer_id, @swimmers, :id, :swimmer_name)
      -#.input.col-md-1
      -#  = f.select :age, SwimmerTime::AGE
      .input.col-md-2
        = f.select :stroke, SwimmerTime::STROKE_TYPES
      .input.col-md-1
        = f.select :distance, SwimmerTime::DISTANCE
      -#.input.col-md-2
      -#  = f.text_field :club
      .input.col-md-2
        = f.select :course, ['Long Course', 'Short Course']
      .input.col-md-2
        = f.text_field :meet,  required: true, label: 'Meet'
      .input.col-md-2
        = f.text_field :venue
      .input.col-md-2
        =f.text_field :date,  required: true
    .row
      .input.col-md-1
        #swimmer-time= f.select :minutes, SwimmerTime::MINUTES,label: 'Min:'
      .input.col-md-1
        = f.select :seconds, SwimmerTime::SECONDS,label: 'Sec:'
      .input.col-md-1
        = f.select :milli_seconds, SwimmerTime:: MILLI_SECONDS, label: 'Ms:'

    .actions.col
      %br
      = f.submit 'Add', :class=>'btn btn-success btn-lg'


  %br
  %br

app/views/swimmer_times/_search_form.html.haml
.times

  = bootstrap_form_tag url: search_swimmer_times_path, remote: true, method: :get  do |f|
    .row
      .input.col-md-2
        = f.select :gender, %w(All Male Female)
      .input.col-md-1
        = f.select :age, %w(All) + SwimmerTime::AGE
      .input.col-md-2
        = f.select :stroke, %w(All) + SwimmerTime::STROKE_TYPES
      .input.col-md-1
        = f.select :distance, %w(All) + SwimmerTime::DISTANCE

      .input.col-md-1
        = f.select :date, %w(All) + SwimmerTime::YEAR, label: 'Year'

      .input.col-md-1
        -#= f.text_field :times,type: hidden
        -#= f.hidden_field :times
    .actions
      = f.submit 'Find', :class=>'btn btn-success btn-sm'
    %br
    %br

app/views/swimmer_times/_swimmer_time.html.haml
%tr{id: swimmer_time.id}
  %td= link_to swimmer_time.swimmer.swimmer_name, swimmer_times_swimmer_path(swimmer_time.swimmer_id)
  %td= swimmer_time.stroke
  %td= swimmer_time.distance
  %td= swimmer_time.convert_times
  -#%td= swimmer_time.club
  %td= swimmer_time.course
  %td= swimmer_time.venue
  %td= swimmer_time.date
  - if ((current_user.role? 'Administrator') || (current_user.role? 'Coach') || (current_user.role? 'Committee'))
    %td= link_to  'Delete', swimmer_time_path(swimmer_time),remote: true, method: :delete, data: {confirm: 'Are you sure'},id:'approve-btn', class: 'icon-remove icon-trash ',style: 'margin-left:0px'
    %td= link_to  'Bml', edit_swimmer_time_path(swimmer_time), class: 'icon-remove icon-edit ',style: 'margin-left:0px'

app/views/swimmer_times/_table.html.haml
.container#result
  .row
    .col-md-10.col-md-offset-1
      %table.table.table-striped.table-responsive.table-customstyle
        %thead
          %tr
          %th Swimmer
          %th Stroke
          %th Length
          %th Times
          -#%th Club
          %th Course
          %th Venue
          %th Date
        %tbody

app/views/swimmer_times/best_times.html.haml
-#- females = SwimmerTime.best_times 'Female'
-#- males = SwimmerTime.best_times 'Male'

#best_timess

  -#.alert.alert-success
  -#  %h2 Best Club Times
  -#%br

  .row
    .col-md-10.col-md-offset-1
      .alert.alert-warning.text-center
        %h3 Girls
        -@females.keys.each do |item|
          .alert.alert-info.text-center
            %caption= " #{item.first} STROKE\t #{item.second} Meters\t #{item.third} year-olds"
          %table.table-bordered.table-condensed.table.table-striped.table-responsive.table-customstyle
            %thead
              %th Name
              %th Time
              %th Meet
              %th Venue
              %th Course
              -#%th Age
              %th Date
            %tbody
              %td= link_to @females[item].first.swimmer.swimmer_name, swimmer_times_swimmer_path(@females[item].first.swimmer_id)
              %td= @females[item].first.convert_times
              %td= @females[item].first.meet
              %td= @females[item].first.venue
              %td= @females[item].first.course
              -#%td= @females[item].first.age
              %td= @females[item].first.date
  .row
    .col-md-10.col-md-offset-1
      .alert.alert-warning.text-center
        %h3 Boys
        -@males.keys.each do |item|
          .alert.alert-info.text-center
            %caption= " #{item.first} STROKE\t #{item.second} Meters\t #{item.third} year-olds"
          %table.table-bordered.table-condensed.table.table-striped.table-responsive.table-customstyle
            %thead
              %th Name
              %th Time
              %th Meet
              %th Venue
              %th Course
              -#%th Age
              %th Date
            %tbody
              %td= link_to @males[item].first.swimmer.swimmer_name, swimmer_times_swimmer_path(@males[item].first.swimmer_id)
              %td= @males[item].first.convert_times
              %td= @males[item].first.meet
              %td= @males[item].first.venue
              %td= @males[item].first.course
              -#%td= @males[item].first.age
              %td= @males[item].first.date

app/views/swimmer_times/create.js.erb
/**
 * Created with JetBrains RubyMine.
 * User: Iman
 * Date: 26/06/2014
 * Time: 22:40
 * To change this template use File | Settings | File Templates.
 */
//$('tbody').empty();

$('#result').show();

$('#result_tbody').append("<%= escape_javascript render(@swimmer_time) %>");

app/views/swimmer_times/create_failure.js.erb
<%  @swimmer_time.errors.each do |error| %>
<% if error.to_s.include?('times') %>
    alert("Time can not be 00:00:00");
<% next %>
<% else %>
    alert("Date can not be in the future")
<% end %>

<% end %>




//alert("Date can not be in the future")

app/views/swimmer_times/destroy.js.erb
$("#<%= @id %>").remove();

app/views/swimmer_times/edit.html.haml
.container
  -#.row{style: 'margin-top:100px'}
  .col-md-4.col-md-offset-3{style: 'margin-top:50px'}

    = bootstrap_form_for @swimmer_time do |f|
      - if @swimmer_time.errors.any?
        #error_explanation.alert.alert-danger
          %h2= "#{pluralize(@swimmer_time.errors.count, "error")} prohibited this swimmer_time from being saved:"
          %ul
            - @swimmer_time.errors.full_messages.each do |msg|
              %li= msg

      #bml.form-inupt
        -##bml-name= f.collection_select(:swimmer_id, @swimmers, :id, :swimmer_name)
        .alert.alert-success
          = @swimmer.swimmer_name
        = f.select :stroke, SwimmerTime::STROKE_TYPES
        = f.select :distance, SwimmerTime::DISTANCE
        = f.text_field :meet
        = f.text_field :venue
        = f.text_field :date
        .row
          .col-md-2
            = f.select :minutes, SwimmerTime::MINUTES, default:'03',label: 'Min:'
          .col-md-2
            = f.select :seconds, SwimmerTime::MINUTES,label: 'Sec:'
          .col-md-2
            = f.select :milli_seconds, SwimmerTime::MINUTES,label: 'Ms:'

      .form-input
        = f.select :bml, %w(Not\ Applicable Winter\ Yorkshire Summer\ Yorkshire Winter\ Regional Summer\ Regional), text: ''
        = f.check_box :asa_meet, text: 'ASA Meet'
        = f.check_box :asa_top_ten, text: 'ASA Meet'
        %br
        = f.submit 'Submit', class: 'btn btn-primary'
      %br
      %br
      %br
      %br


  %br
  %br
:javascript
  $('#bml-name').hide()

app/views/swimmer_times/index.html.haml
%br
%br
.container
  #tabs
    %ul
      %li#search
        %a{href: '#fragment-1', id: 'search_fragment'} Search
      -#%li#charts
      -#  %a{href: '#fragment-2',id: 'charts_fragment'} Charts
      %li#best-times
        %a{href: '#fragment-3',id: 'best_times_fragment'} Best Times

      - if( (current_user.role? 'Coach') || (current_user.role? 'Committee') || (current_user.role? 'Administrator'))
        %li#add-times
          %a{href: '#fragment-4',id:'add_times_fragment'} Add Times

    #fragment-1
      = render 'swimmer_times/search_form'

    -##fragment-2
    -#  = line_chart({20.day.ago => 5, 1368174456 => 10, "2013-05-07 00:00:00 UTC" => 7}, id:'Iman')

    #fragment-3

      = render partial: 'best_times', lacals: {males: @males, females: @females}



    - if( (current_user.role? 'Coach') || (current_user.role? 'Committee') || (current_user.role? 'Administrator'))

      #fragment-4
        = render 'form'

  .alert-message
  #result
    .row
      .col-md-10.col-md-offset-1
        %table.table.table-striped.table-responsive.table-customstyle
          %thead
            %tr
            %th Swimmer
            %th Stroke
            %th Length
            %th Times
            -#%th Club
            %th Course
            %th Venue
            %th Date
            - if ((current_user.role? 'Administrator') || (current_user.role? 'Coach') || (current_user.role? 'Committee'))
              %th Action
              %th BML
          %tbody#result_tbody
            -#= render @swimmer_times




  %br

:javascript

app/views/swimmer_times/new.html.haml
%h1 Add Club Times

= render 'form'

#tb.row
  .col-md-10.col-md-offset-1
    %h3 Swimmer Times
    %table.table.table-striped.table-responsive.table-customstyle
      %thead
        %tr
          %th Swimmer Name
          %th Stroke
          %th Distance
          %th Times
          -#%th Club
          %th Venue
          %th Date



      %tbody
      #swimmer_time

= link_to 'Back', swimmer_times_path

app/views/swimmer_times/search.js.erb
$('#result_alert').remove();
$('#result').hide();
$('#result_tbody').empty();


<% if @swimmer_times.size > 0 %>

    $('#result').show();

    $('#result_tbody').append("<%= escape_javascript render(@swimmer_times) %>");

<% else %>

    $('.alert-message').append("<div class='alert alert-danger' id='result_alert' role='alert'>No Result Found!</div>");

<% end %>

app/views/swimmer_times/show.html.haml
%p#notice= notice

%p
  %b Swimmer:
  = @swimmer_time.swimmer
%p
  %b Stroke:
  = @swimmer_time.stroke
%p
  %b Length:
  = @swimmer_time.distance
%p
  %b Times:
  = @swimmer_time.times
%p
  %b Club:
  = @swimmer_time.club
%p
  %b Venue:
  = @swimmer_time.venue
%p
  %b Date:
  = @swimmer_time.date

= link_to 'Edit', edit_swimmer_time_path(@swimmer_time)
\|
= link_to 'Back', swimmer_times_path